import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "e-Wings",
  description: "Generated by e-Wings",
  icons: {
    icon: "/company logo.jpeg", // or "/dravinlabs-logo.png" if using a PNG
    shortcut: "/company logo.jpeg",
    //apple: "/apple-touch-icon.png", // optional, if you have an Apple icon
  },
};
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
