import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import FontLoader from "@/components/FontLoader";
import ThemeProvider from "@/components/ThemeProvider";
import { Toaster } from "sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "e-Wings",
  description: "Generated by e-Wings",
  icons: {
    icon: "/company logo.jpeg",
    shortcut: "/company logo.jpeg",
  },
  viewport: {
    width: 'device-width',
    initialScale: 1,
    maximumScale: 5,
    userScalable: true,
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider />
        <FontLoader />
        {children}
        <Toaster position="top-right" richColors />
      </body>
    </html>
  );
}
