export const LOGIN_CONSTANT = {
 USER_TOKEN: 'token',
 USER_ID: 'userId',
 FULL_NAME: 'fullName',
 MOBILE_NUMBER: 'mobileNumber',
 ADDRESS: 'address',
 PINCODE: 'pinCode',
 CITY: 'city',
 EMAIL: 'email',
 GSTID: 'gstId',
 USER_PROFILE_DATA: 'user_profile_data',
 DDO_ID_NOTFOUND: 'DDO ID not found. Please login again.',
 success: 'success',
 error: 'error',
 amountDeclared: 'Amount Declared',
 amountPaid: 'Amount Paid',
penaltyAmount: 'Penalty Amount',
NO_FIE_SELECTED: 'No file selected',
ONLY_PDF_ALLOWED: 'Only PDF files are allowed.',
SELECT_FINANCIAL: 'Please select Financial Year',
SELECT_MONTH: 'Please select Month',
SELECT_ARN_NUMBER: 'Please enter ARN Number',
SELECT_ARN_DATE: 'Please select ARN Date',
ENTER_AMOUNT_DECLARED: "Please enter Amount Declared",
ENTER_AMOUNT_PAID: "Please enter Amount Paid",
UPLOAD_ACK_PDF: "Please upload Acknowledgement PDF",
SOMETHING_WENT_WRONG: "Something went wrong",
DDO_CODE:'DDO Code',
GST_CODE:'GST Code',
OFFICE_ADDRESS:'Office Address',

}
export const FOOTER_TEXT = "© 2025 Dravinlabs Technology Pvt. Ltd. All rights reserved.";
